<section class="talking_heads_carousel">
    <div id="myDiv"></div>
    <!-- carousel data -->
    <div id="carouselData" style="display: none;">
        <!-- image datalist category 1 -->
        <ul data-cat="Category one">
            <?php include ("includes/carousel-1.php");?>
        </ul>
    </div>
</section>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
<script src="js/FWDUltimate3DCarousel_uncompressed.js"></script>
<script>
    FWDU3DCarUtils.onReady( function () {
        var carousel = new FWDUltimate3DCarousel( {
            //required settings
            carouselHolderDivId: "myDiv",
            carouselDataListDivId: "carouselData",
            displayType: "fluidwidth",
            autoScale: "yes",
            carouselWidth: 940,
            carouselHeight: 460,
            skinPath: "load/skin_modern_silver",
            //main settings
            backgroundColor: "#CCDDFF",
            backgroundImagePath: "load/skin_modern_silver/background.png",
            thumbnailsBackgroundImagePath: "",
            scrollbarBackgroundImagePath: "load/skin_modern_silver/scrollbarBackground.png",
            backgroundRepeat: "repeat-x",
            carouselStartPosition: "left",
            carouselTopology: "normal",
            carouselXRadius: 700,
            carouselYRadius: 80,
            carouselXRotation: 10,
            carouselYOffset: -60,
            showCenterImage: "yes",
            centerImagePath: "load/TalkingHeads.png",
            centerImageYOffset: 60,
            showDisplay2DAlways: "no",
            slideshowDelay: 5000,
            autoplay: "yes",
            showPrevButton: "yes",
            showNextButton: "yes",
            showSlideshowButton: "yes",
            disableNextAndPrevButtonsOnMobile: "no",
            controlsMaxWidth: 1100,
            controlsHeight: 62,
            controlsPosition: "bottom",
            slideshowTimerColor: "#FFF",
            rightClickContextMenu: "default",
            addKeyboardSupport: "yes",
            fluidWidthZIndex: 1000,
            //thumbnail settings
            thumbnailWidth: 160,
            thumbnailHeight: 180,
            thumbnailBorderSize: 0,
            thumbnailMinimumAlpha: .0,
            thumbnailBackgroundColor: "#0056BF",
            thumbnailBorderColor1: "#fcfdfd",
            thumbnailBorderColor2: "#6DABFF",
            transparentImages: "yes",
            maxNumberOfThumbnailsOnMobile: 13,
            showThumbnailsGradient: "no",
            showThumbnailsHtmlContent: "no",
            textBackgroundColor: "#0056BF",
            textBackgroundOpacity: .2,
            showText: "yes",
            showTextBackgroundImage: "yes",
            showFullTextWithoutHover: "yes",
            showThumbnailBoxShadow: "no",
            thumbnailBoxShadowCss: "0px 2px 2px #555555",
            showReflection: "yes",
            reflectionHeight: 60,
            reflectionDistance: 0,
            reflectionOpacity: .3,
            //scrollbar settings
            showScrollbar: "no",
            disableScrollbarOnMobile: "yes",
            enableMouseWheelScroll: "yes",
            scrollbarHandlerWidth: 300,
            scrollbarTextColorNormal: "#777777",
            scrollbarTextColorSelected: "#000000",
            //combobox settings
            showComboBox: "no",
            startAtCategory: 1,
            selectLabel: "SELECT CATEGORIES",
            allCategoriesLabel: "All Categories",
            showAllCategories: "no",
            comboBoxPosition: "topright",
            selectorBackgroundNormalColor1: "#fcfdfd",
            selectorBackgroundNormalColor2: "#e4e4e4",
            selectorBackgroundSelectedColor1: "#a7a7a7",
            selectorBackgroundSelectedColor2: "#8e8e8e",
            selectorTextNormalColor: "#8b8b8b",
            selectorTextSelectedColor: "#FFFFFF",
            buttonBackgroundNormalColor1: "#e7e7e7",
            buttonBackgroundNormalColor2: "#e7e7e7",
            buttonBackgroundSelectedColor1: "#a7a7a7",
            buttonBackgroundSelectedColor2: "#8e8e8e",
            buttonTextNormalColor: "#000000",
            buttonTextSelectedColor: "#FFFFFF",
            comboBoxShadowColor: "#000000",
            comboBoxHorizontalMargins: 12,
            comboBoxVerticalMargins: 20,
            comboBoxCornerRadius: 0,
            //lightbox settings
            addLightBoxKeyboardSupport: "yes",
            showLightBoxNextAndPrevButtons: "yes",
            showLightBoxZoomButton: "yes",
            showLightBoxInfoButton: "no",
            showLighBoxSlideShowButton: "yes",
            showLightBoxInfoWindowByDefault: "no",
            slideShowAutoPlay: "no",
            lightBoxVideoAutoPlay: "no",
            lightBoxVideoWidth: 540,
            lightBoxVideoHeight: 360,
            lightBoxIframeWidth: 540,
            lightBoxIframeHeight: 360,
            lightBoxBackgroundColor: "#000000",
            lightBoxInfoWindowBackgroundColor: "#FFFFFF",
            lightBoxItemBorderColor1: "#fcfdfd",
            lightBoxItemBorderColor2: "#e4FFe4",
            lightBoxItemBackgroundColor: "#6DABFF",
            lightBoxMainBackgroundOpacity: .8,
            lightBoxInfoWindowBackgroundOpacity: .9,
            lightBoxBorderSize: 5,
            lightBoxBorderRadius: 0,
            lightBoxSlideShowDelay: 4000
        } );
    } );
</script>